version = 1
SPDX-PackageName = "cloud-provider-ironcore"
SPDX-PackageSupplier = "IronCore authors <ospo@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/ironcore-dev/cloud-provider-ironcore"

[[annotations]]
path = [
    ".github/**",
    ".gitignore",
    ".golangci.yml",
    ".dockerignore",
    "CODE_OF_CONDUCT.md",
    "CODEOWNERS",
    "Dockerfile",
    "Makefile",
    "config/**",
    "go.mod",
    "go.sum",
    "hack/**",
    "REUSE.toml",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["docs/**", "README.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"
