apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: occm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: occm
subjects:
  - kind: ServiceAccount
    name: cloud-controller-manager
  - kind: ServiceAccount
    name: onmetal
    namespace: kube-system